/**
 * FontAwesome free solid icons for navigation and UI (from previous RN app).
 */
import {
  faHouse,
  faCompass,
  faCartShopping,
  faUser,
  faSearch,
  faBars,
  faXmark,
  faGift,
  faBoxOpen,
  faCalendar,
  faFire,
  faBook,
  faChevronRight,
  faCamera,
  faGear,
  faBell,
  faMessage,
  faExplosion,
  faBarcode,
  faChildReaching,
  faFingerprint,
  faMicrophone,
  faClockRotateLeft,
  faImage,
  faStar,
  faChevronDown,
  faAnglesLeft,
  faAnglesRight,
  faFilter,
  faTrash,
  faPlus,
  faPaperPlane,
  faArrowUp,
  faThumbsUp,
  faUtensils,
  faDice,
  faMenorah,
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  home: faHouse,
  browse: faCompass,
  cart: faCartShopping,
  user: faUser,
  search: faSearch,
  menu: faBars,
  close: faXmark,
  gift: faGift,
  boxOpen: faBoxOpen,
  calendar: faCalendar,
  candle: faFire,
  menorah: faMenorah,
  book: faBook,
  chevronRight: faChevronRight,
  camera: faCamera,
  gear: faGear,
  bell: faBell,
  message: faMessage,
  explosion: faExplosion,
  barcode: faBarcode,
  childReaching: faChildReaching,
  fingerprint: faFingerprint,
  microphone: faMicrophone,
  clockHistory: faClockRotateLeft,
  image: faImage,
  star: faStar,
  chevronDown: faChevronDown,
  chevronsLeft: faAnglesLeft,
  chevronsRight: faAnglesRight,
  filter: faFilter,
  trash: faTrash,
  plus: faPlus,
  paperPlane: faPaperPlane,
  arrowUp: faArrowUp,
  thumbsUp: faThumbsUp,
  utensils: faUtensils,
  dice: faDice,
} as const;

export type IconName = keyof typeof icons;
